/**
 * The starter recipes: 100 everyday dishes from the Wikibooks Cookbook (CC BY-SA 4.0), so
 * "what can I make?" has something to chew on before her own books are photographed in.
 *
 * Data plus a loader, nothing else. `starter.json` is generated by
 * `scripts/fetch-starter.mjs` and committed; see README.md here for the source, the
 * licence and how to regenerate. The JSON is loaded lazily so the 270 KB only travels
 * when she presses the button in Settings, and it goes through `repo.addStarterRecipes`
 * — never straight into the database.
 */

import type { RecipeSource } from '../lib/types'

export type StarterRecipe = {
  /** Minted once by the script and kept forever — what makes re-adding a no-op. */
  uuid: string
  title: string
  source: RecipeSource
  yield?: { text: string }
  ingredients: { heading?: string; items: { raw: string; optional?: boolean }[] }[]
  steps: { n: number; text: string }[]
  tags: string[]
}

/** Kept in step with starter.json by the test in __tests__/starter.test.ts. */
export const STARTER_COUNT = 100

export async function loadStarterRecipes(): Promise<StarterRecipe[]> {
  const module = await import('./starter.json')
  return module.default as StarterRecipe[]
}
